[alembic]
script_location = alembic

# IMPORTANT:
# Alembic uses Python ConfigParser, which treats '%' as interpolation.
# To avoid crashes, ALWAYS escape '%' as '%%' in this file.
#
# Your current password does not contain '%', so no escaping is needed.
# This line is safe as-is.
sqlalchemy.url = mysql+pymysql://admin:S7rKrvPyTfMkLUyXqUwR@sentinelcybercop.ce9u88wwevvx.us-east-1.rds.amazonaws.com:3306/sentinelops


# Logging
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
