"""Fix plugin model

Revision ID: 3b10c3f1d108
Revises: deb1c4a12f04
Create Date: 2026-04-26 14:33:52.674954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b10c3f1d108'
down_revision: Union[str, None] = 'deb1c4a12f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('plugin_id'), table_name='plugin_settings')
    op.drop_table('plugin_settings')
    op.drop_table('user_roles')
    op.drop_index(op.f('name'), table_name='plugin_categories')
    op.drop_table('plugin_categories')
    op.drop_table('audit_events')
    op.alter_column('plugins', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('plugins', 'name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_plugins_id'), 'plugins', ['id'], unique=False)
    op.create_unique_constraint(None, 'plugins', ['name'])
    op.drop_constraint(op.f('plugins_ibfk_1'), 'plugins', type_='foreignkey')
    op.drop_column('plugins', 'category_id')
    op.drop_column('plugins', 'version')
    op.drop_column('plugins', 'enabled')
    op.drop_column('plugins', 'created_at')
    op.drop_column('plugins', 'entrypoint')
    op.alter_column('sessions', 'session_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Random server‑side session token',
               existing_nullable=False)
    op.alter_column('sessions', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               comment='Browser or device information',
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment='IPv4 or IPv6 address',
               existing_nullable=True)
    op.alter_column('sessions', 'device_fingerprint',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Optional client-side fingerprint for device binding',
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Session creation timestamp (UTC)')
    op.alter_column('sessions', 'last_seen_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               comment='Last activity timestamp (UTC)')
    op.alter_column('sessions', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='Session expiration timestamp (UTC)',
               existing_nullable=False)
    op.drop_index(op.f('session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('sessions_ibfk_1'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'session_token')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'user'"), nullable=False))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('session_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_ibfk_1'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.create_index(op.f('session_token'), 'sessions', ['session_token'], unique=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Session expiration timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('sessions', 'last_seen_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               nullable=True,
               comment=None,
               existing_comment='Last activity timestamp (UTC)')
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Session creation timestamp (UTC)')
    op.alter_column('sessions', 'device_fingerprint',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Optional client-side fingerprint for device binding',
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment=None,
               existing_comment='IPv4 or IPv6 address',
               existing_nullable=True)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Browser or device information',
               existing_nullable=True)
    op.alter_column('sessions', 'session_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Random server‑side session token',
               existing_nullable=False)
    op.add_column('plugins', sa.Column('entrypoint', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('plugins', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('plugins', sa.Column('enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.add_column('plugins', sa.Column('version', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('plugins', sa.Column('category_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('plugins_ibfk_1'), 'plugins', 'plugin_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'plugins', type_='unique')
    op.drop_index(op.f('ix_plugins_id'), table_name='plugins')
    op.alter_column('plugins', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('plugins', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('audit_events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('event_details', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_events_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plugin_categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'plugin_categories', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plugin_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plugin_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('setting_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('setting_value', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('plugin_settings_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('plugin_id'), 'plugin_settings', ['plugin_id', 'setting_key'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('setting_value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
