"""sync models with db

Revision ID: 547d76fa4ac1
Revises: 24d85e9dde70
Create Date: 2026-04-26 21:15:11.222188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '547d76fa4ac1'
down_revision: Union[str, None] = '24d85e9dde70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint(op.f('plugin_settings_ibfk_1'), 'plugin_settings', type_='foreignkey')
    op.create_foreign_key(None, 'plugin_settings', 'plugins', ['plugin_id'], ['id'])
    op.drop_constraint(op.f('plugins_ibfk_1'), 'plugins', type_='foreignkey')
    op.create_foreign_key(None, 'plugins', 'plugin_categories', ['category_id'], ['id'])
    op.alter_column('sessions', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('sessions', 'last_seen_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('sessions_ibfk_1'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_roles', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'mfa_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('users', 'mfa_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               server_default=sa.text("'user'"),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('user_roles', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_ibfk_1'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.create_index(op.f('session_token'), 'sessions', ['session_token'], unique=True)
    op.alter_column('sessions', 'last_seen_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'plugins', type_='foreignkey')
    op.create_foreign_key(op.f('plugins_ibfk_1'), 'plugins', 'plugin_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'plugin_settings', type_='foreignkey')
    op.create_foreign_key(op.f('plugin_settings_ibfk_1'), 'plugin_settings', 'plugins', ['plugin_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('plugin_id'), 'plugin_settings', ['plugin_id', 'setting_key'], unique=True)
    op.alter_column('audit_events', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
